# Generated by Django 5.0.6 on 2024-06-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_internal_mapping', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='boards',
            fields=[
                ('board', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='defaultName', max_length=100, unique=True)),
                ('row_dim', models.IntegerField()),
                ('column_dim', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='io_type',
            fields=[
                ('io_type_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('io_type_symbol', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('first_interface', models.CharField(max_length=255)),
                ('second_interface', models.CharField(max_length=255)),
                ('nom_link', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='resource_name',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='signal', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.folder')),
            ],
        ),
        migrations.CreateModel(
            name='interfaces',
            fields=[
                ('interface', models.TextField(primary_key=True, serialize=False)),
                ('board1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board1_interfaces', to='app.boards')),
                ('board2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board2_interfaces', to='app.boards')),
            ],
        ),
        migrations.CreateModel(
            name='interfaceConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.TextField(blank=True, null=True)),
                ('connecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='app.connector')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='app.interfaces')),
            ],
        ),
        migrations.CreateModel(
            name='connecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_row', models.IntegerField()),
                ('dimension_column', models.IntegerField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected', to='app.interfaces')),
            ],
        ),
        migrations.CreateModel(
            name='IO_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=255)),
                ('from_to', models.CharField(max_length=255)),
                ('source_destination_board', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('connector', models.CharField(max_length=255)),
                ('assigned_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assigned_resources')),
            ],
        ),
        migrations.AddField(
            model_name='assigned_resources',
            name='io_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.io_type'),
        ),
        migrations.CreateModel(
            name='association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_resource', models.IntegerField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='app.interfaces')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='app.resource_name')),
            ],
        ),
        migrations.CreateModel(
            name='resources_categories',
            fields=[
                ('category', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, null=True)),
                ('io_type', models.ManyToManyField(related_name='resources_categories', to='app.io_type')),
            ],
        ),
        migrations.CreateModel(
            name='modele_io_mapping',
            fields=[
                ('modele_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('interfaces', models.ManyToManyField(to='app.interfaces')),
                ('iotypes', models.ManyToManyField(to='app.io_type')),
                ('links', models.ManyToManyField(to='app.link')),
                ('resource_names', models.ManyToManyField(to='app.resource_name')),
                ('resources', models.ManyToManyField(to='app.resources_categories')),
            ],
        ),
        migrations.AddField(
            model_name='assigned_resources',
            name='category',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='app.resources_categories'),
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_row', models.IntegerField()),
                ('num_column', models.IntegerField()),
                ('connecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.connecteur')),
                ('signal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.signal')),
            ],
        ),
        migrations.AddField(
            model_name='assigned_resources',
            name='signal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.signal'),
        ),
        migrations.CreateModel(
            name='wirings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_signal', models.TextField(blank=True)),
                ('second_signal', models.TextField(blank=True)),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wirings', to='app.link')),
            ],
        ),
    ]
